/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import controller.Controller;
/**
 *
 * @author Dell
 */
public class GameInterface extends javax.swing.JFrame {

    /**
     * Creates new form ui
     */
    public Controller controller;
    boolean isPlaying = false;
    
    public GameInterface() {
        this.setTitle("NPG");
        initComponents();
        //lay ra size do nguoi dung chon
        controller = new Controller();
        String gameSize = cbxSize.getSelectedItem().toString();
        int size = Integer.parseInt(gameSize.split("x")[0].trim());
        //đặt size cho game
        controller.setSize(size);
        controller.addButtons(jPnlAreaForPlay);
        controller.setButtonValues();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlAreaForPlay = new javax.swing.JPanel();
        lblSize = new javax.swing.JLabel();
        labelMoveCount = new javax.swing.JLabel();
        lblElapsedTime = new javax.swing.JLabel();
        cbxSize = new javax.swing.JComboBox<>();
        btnNewGame = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPnlAreaForPlay.setPreferredSize(new java.awt.Dimension(330, 330));

        javax.swing.GroupLayout jPnlAreaForPlayLayout = new javax.swing.GroupLayout(jPnlAreaForPlay);
        jPnlAreaForPlay.setLayout(jPnlAreaForPlayLayout);
        jPnlAreaForPlayLayout.setHorizontalGroup(
            jPnlAreaForPlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        jPnlAreaForPlayLayout.setVerticalGroup(
            jPnlAreaForPlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );

        lblSize.setText("Size:");

        labelMoveCount.setText("Move count:");

        lblElapsedTime.setText("Elapsed time:");

        cbxSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3x3", "4x4", "5x5", "6x6", "7x7", "8x8", "9x9", "10x10", " " }));
        cbxSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSizeActionPerformed(evt);
            }
        });

        btnNewGame.setText("New game");
        btnNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewGameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblElapsedTime)
                            .addComponent(labelMoveCount)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSize)
                                .addGap(63, 63, 63)
                                .addComponent(cbxSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPnlAreaForPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(btnNewGame)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPnlAreaForPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSize)
                    .addComponent(cbxSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelMoveCount)
                .addGap(18, 18, 18)
                .addComponent(lblElapsedTime)
                .addGap(18, 18, 18)
                .addComponent(btnNewGame)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxSizeActionPerformed

    private void btnNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewGameActionPerformed
        // TODO add your handling code here:
        int size;
        String gameSize = cbxSize.getSelectedItem().toString();//vì hàm getSelectedItem trả về 1 object
        try {
            size = Integer.parseInt(gameSize.split("x")[0].trim());
        } catch (Exception e) {
            return;
        }
        //cắt chuỗi để sử lý
        if (isPlaying) {
            controller.getTimer().stop();//Dừng cái bộ đếm thời gian game cũ lại đã
        }
        controller.setTimeCounter(0);//đặt bộ đếm thời gian về 0
        controller.setMoveCounter(0);//đặt bộ đếm bước về 0
        controller.setSize(size);//đặt size cho game
        labelMoveCount.setText("Move count: 0");   //hiển thị ra bộ đếm về 0
        controller.setTimer(lblElapsedTime);//xử lý hiện vào frame
        if (size != 3 || isPlaying == true) {
            controller.addButtons(jPnlAreaForPlay);
            controller.setButtonValues();
        }
        controller.swapButtons(labelMoveCount);
        isPlaying = true;
    }//GEN-LAST:event_btnNewGameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNewGame;
    private javax.swing.JComboBox<String> cbxSize;
    private javax.swing.JPanel jPnlAreaForPlay;
    private javax.swing.JLabel labelMoveCount;
    private javax.swing.JLabel lblElapsedTime;
    private javax.swing.JLabel lblSize;
    // End of variables declaration//GEN-END:variables
}
